sources:
  - name: curve
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/{env.THE_GRAPH_API_TOKEN}/subgraphs/id/GAGwGKc4ArNKKq9eFTcwgd1UGymvqhTier9Npqo1YvZB
    transforms:
      - blockTracking:
          validateSchema: true
documents:
  - ./src/queries/curve.graphql
